package com.somboi.rodaimpian.gdxnew.onlineclasses;

public enum GameState {
    HOSTDISCONNECT,
    START,
    SHOWQUESTIONS,
    STARTURN,
    SHOWMENU,
    SPINSCREEN,
    SHOWCONSONANT,
    SHOWVOCAL,
    FINISHSPIN,
    PREPAREENVELOPE,
    FINISHROUND,
    CONTINUETURN,
    CHANGETURN,
    COMPLETE,
    INCREASEROUND,
    SPINBONUSWHEEL,
    OCCUPIED
}

